# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ba6c2ce7074448b51c0140de822712ec153a182cc13e673e9e3e1fa96c4e2c3f8840ac898302cb22f3d9e531ede4a6acaf57d27112fe944067456fba4576098

test:
  secret_key_base: 645c65227c141061f36e7eb5120cbc8dd5f9dd4c961a75f8a89c927c82d67d19e2178c204ffba0039df391489c43ff34ff47774f0790ebf3e357a8035093073d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
